from setuptools import setup, find_packages

setup(
    name="dtfb",
    version="0.1.0",
    description="Automated CLI pipeline turning dealership vehicle inventory into AI-enhanced social media posts, hero visuals, and video carousels.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="asuramaya",
    url="https://github.com/asuramaya/dtfb",
    project_urls={
        "Source": "https://github.com/asuramaya/dtfb",
        "Tracker": "https://github.com/asuramaya/dtfb/issues",
    },
    license="MIT",
    keywords="dealership automotive facebook-marketplace instagram social-media computer-vision clip rembg",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Multimedia :: Graphics",
        "Topic :: Multimedia :: Video",
        "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
    ],
    python_requires=">=3.11",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    package_data={
        "dtfb": [
            "imaging/templates/*",
            "imaging/calibration/**/*",
        ],
    },
    install_requires=[
        "pillow>=10",
        "playwright>=1.40",
        "requests>=2.31",
        "numpy>=1.26",
        "torch>=2.0",
        "torchvision>=0.15",
        "transformers>=4.30",
        "onnxruntime>=1.16.0",
        "open_clip_torch>=2.20",
        "rembg>=2.0",
        "imagehash>=4.3",
        "spandrel>=0.4",
        "scipy>=1.10",
        "opencv-python-headless>=4.8",
    ],
    extras_require={
        "dev": ["pytest>=8", "pytest-xdist>=3"],
    },
    entry_points={
        "console_scripts": [
            "dtfb = dtfb.cli:main",
            "compose = dtfb.compose_cli:main",
            "hero-video = dtfb.hero_video_cli:main",
            "posts = dtfb.posts_cli:main",
            "recompose = dtfb.recompose_cli:main",
            "inventory-sync = dtfb.inventory_sync:main",
        ],
    },
)
